@startuml
|Kunde|
start
:Login/opret;
|System|
:Validerer login/opretter bruger;
|Kunde|
:Sammensætter en carport/bestiller;
|System|
:Generere en tegning af carporten og en pris;
|Kunde|
:Køber carport;
|System|
: Genere stykliste, tegning og tilføjer en ordre;
|Kunde|
: Tjekker ordre under min side;

@enduml
