@startuml

class Customer {
- Brugernavn
- Email
- Password
- Role
- Adresse
- By
- Postnummer
- Navn
- Telefonnr
}

class Carport {
- Pris
- Tagtype
- Tagtype mål
- Tag hældning
- Carport Bredde
- Carport Længde
- Redskabs bredde
- Redskabs længde
}

class Order {
- Dato
- Pris
- Brugernavn
- Email
- Carport
}

@enduml