@startuml

class Kunde {
- Brugernavn
- Email
- Password
- Role
- Adresse
- By
- Postnummer
- Navn
- Telefonnr
}

class Carport {
- Pris
- Carport Bredde
- Carport Længde
- Redskabs bredde
- Redskabs længde
- Materialer
}

class Item {
- Beskrivelse
- Længde
- Pris
- Enhed
- Navn/beskrivelse
}

class Variant {
- Beskrivelse
- Pris
- Enhed
- Navn/beskrivelse
}
class Ordre {
- Dato
- Pris
- Brugernavn
- Email
- Carport
}

class System {
- Stykliste
- SVG
}

Kunde "1"--"*" Ordre : Has
Ordre "*"--"*" Carport: Contains
Carport "1"--"More" Item : Contains
Carport "1"--"More" Variant : Contains
Ordre "1"--"*" System : Contains

@enduml